Add editable tagline to testimonial component
SSWConsulting/SSW.Website pull request #1031
Opened 2023-07-14 05:39 UTC by jackreimers

Adds an editable tagline to the testimonial row component.
The tagline can be edited per page in Tina.

Fixes #604 

Affected routes:

- `/consulting/*`
- `/training/internship-fullstack`

![image](https://github.com/SSWConsulting/SSW.Website/assets/10693364/a1fc3195-2961-4d6d-a823-0b4fa7016c04)

2023-07-14 06:56 UTC, Harry-Ross requested changes
Hi Jack, I think instead of having a schema for the testimonial row component, it would be better to add a `rich-text` field to the consulting and training pages, that is rendered above the testimonial row like so:
![image](https://github.com/SSWConsulting/SSW.Website/assets/20507092/b2419965-4d08-4d10-9521-ee0e33d863f6)

This is because the testimonial fetching is hard coded into each page, and is loaded through getStaticProps. This is also better because it means that non-tech people can edit the "What do people say?" section.

2023-07-17 02:02 UTC, jackreimers commented
@Harry-Ross I don't see a situation where the title on the testimonial would need to be changed, but the tagline does need to be different on each page as Uly doesn't want a tagline on the consulting pages.

Having the title and tagline in a markdown would mean we would have to set the title for each page as well which could be time consuming.

@bradystroud

2023-07-17 23:23 UTC, Harry-Ross commented
> @Harry-Ross I don't see a situation where the title on the testimonial would need to be changed, but the tagline does need to be different on each page as Uly doesn't want a tagline on the consulting pages.
> 
> Having the title and tagline in a markdown would mean we would have to set the title for each page as well which could be time consuming.
> 
> @bradystroud

Upon reflection, you are right - approved

2023-07-17 23:24 UTC, Harry-Ross approved these changes

2023-07-17 23:50 UTC, merged