Dotnet superpowers
SSWConsulting/SSW.Website pull request #1126
Opened 2023-07-27 02:12 UTC by KristenHu

Related to #596 , merge the net superpower tour page.

Affected routes:

- `/events/net-superpowers-tour`

Add done video, screenshots

2023-07-27 04:07 UTC, amankumarrr requested changes
<img width="960" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/ef965947-3004-420c-88e2-fe6d5ef11511">

Dates are not same as on actual site

2023-07-27 04:10 UTC, amankumarrr requested changes
<img width="979" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/4b5e0754-b889-4625-b921-73fca94f64ab">

There are 5 presenters on the page

2023-07-27 04:12 UTC, amankumarrr requested changes
<img width="1007" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/6efa0fca-fdee-4ffe-b4e9-56dcbc9722f6">

This content should be above the video and also some of the content is missing ther e

2023-07-28 00:14 UTC, amankumarrr approved these changes
LGTM 🌟

2023-07-28 04:10 UTC, Harry-Ross commented on content/events/net-superpowers-tour.mdx
> +              * write once and run anywhere with .NET
Capitalise this word :)

2023-07-28 04:10 UTC, Harry-Ross approved these changes
Other than the small typo, LGTM

2023-07-28 06:08 UTC, KristenHu commented on content/events/net-superpowers-tour.mdx
> +              * write once and run anywhere with .NET
Thanks, fixed😃

2023-07-28 06:45 UTC, merged