💄New Design - Upcoming events
SSWConsulting/SSW.Website pull request #1150
Opened 2023-08-01 06:00 UTC by amankumarrr

Fixes #1148 

Affected routes:

- `/` 

Add done video, screenshots
<img width="1261" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/ffb58d3a-7671-4b48-a9f8-07e68117b951">

**Figure: newly designed upcoming event component v1**

<img width="767" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/6bac9a98-5a12-486a-9d49-237e197cbe97">

**Figure: newly designed upcoming event component v2**

<img width="190" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/21eaab4a-6529-4a69-a205-a2da154518a5">

**Figure: newly designed upcoming event component v2 in mobile view**

2023-08-01 23:35 UTC, jaydenalchin commented
Hi @amankumarrr CC @tiagov8 

1. We shouldn't have a scrollbar here. I would just show the 5 upcoming events as demonstrated above.
2. To compensate, we should add more emphasis to the "More Events" button
3. Add a verb to the button i.e. "**See** more events" to follow best practice
4. The card border colour is too light & low contrast against white, it should be #CCCCCC
5. Increase the gap between these two sections. The grey events bg was doing a lot of work separating the upcoming events section from the text-heavy section to the left.
6. These headings should also be h2 not h1, and match the h2's "Contact Us" / "tv.ssw.com" in the section below this. 

Here's an example of some of my feedback actioned in my browser: 

![image](https://github.com/SSWConsulting/SSW.Website/assets/75593567/4262ce80-126e-4790-8c6d-d7c15af0735d)

**Figure: Section gap (5rem), red button, updated button text**

2023-08-02 02:41 UTC, bradystroud approved these changes
LGTM

2023-08-02 06:07 UTC, jaydenalchin requested changes

2023-08-02 06:07 UTC, jaydenalchin commented on pages/[filename].tsx
> +        <Container className={"flex-1 pt-4"}>
```suggestion
        <Container className={"flex-1"}>
```

2023-08-02 06:12 UTC, jaydenalchin commented
@amankumarrr @bradystroud

1. The cards themselves should be clickable, not just the title text
2. The cards need hover styling. This is still TBD for the proposed rules cards - I would suggest just adding border-colour #333333 on hover and we can reevaluate later if needed for consistency.

2023-08-02 07:03 UTC, amankumarrr commented
> @amankumarrr @bradystroud
> 
> 1. The cards themselves should be clickable, not just the title text
> 2. The cards need hover styling. This is still TBD for the proposed rules cards - I would suggest just adding border-colour #333333 on hover and we can reevaluate later if needed for consistency.

@jaydenalchin  Done

2023-08-02 07:07 UTC, jaydenalchin approved these changes
LGTM 🚀

2023-08-02 07:08 UTC, merged