Custom training options
SSWConsulting/SSW.Website pull request #1260
Opened 2023-08-17 10:02 UTC by KristenHu

Fixes #601 - Migrate events page: Custom Training Options

Affected routes:

-`/events/custom-training-options`

Add done video, screenshots

2023-08-19 23:17 UTC, bradystroud requested changes
<img width="1800" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/38869720/5eee426e-b5c0-4ee1-ae12-f2834dcf2ff0">
These testimonials should use the testimonials component

FYI the url in your description gives a 404, it should be `events/customized-courses`

2023-09-04 20:31 UTC, bradystroud commented
Hey @KristenHu 
Is this one ready for review?
Seems like my requested changes haven't been fixed yet

2023-09-05 08:22 UTC, KristenHu commented
> Hey @KristenHu Is this one ready for review? Seems like my requested changes haven't been fixed yet
> 
> Please make this a draft PR if its not ready for review

Hey @bradystroud ,
Yes, It's ready for review now. Ken and I just got test pass for the banner of the page this morning, I've pushed it to the PR.

As per our conversation in Teams, we won't use testimonials component currently😊
![image](https://github.com/SSWConsulting/SSW.Website/assets/52522913/5fe7a08a-f51f-4bb1-b62f-bdcac984a9be)

2023-09-06 23:01 UTC, bradystroud requested changes

2023-09-06 23:01 UTC, bradystroud commented on public/images/background/SSWTraining.png
This file isn't used, can you remove?

2023-09-06 23:01 UTC, bradystroud commented on content/events/customized-courses.mdx
> +    content: "## Keep up with the latest developments on Microsoft Technologies\n\n✅Hands-on training\n\n✅High quality material\n\n✅Real world examples\n\nWe believe that everyone should have access
```suggestion
    content: "## Keep up with the latest developments on Microsoft Technologies\n\n✅Hands-on training\n\n✅High quality material\n\n✅Real world examples\n\nWe believe that everyone should have access to expert advice. SSW provides high quality hands-on developer training so you can stay in front. Our instructors have substantial experience and speak at development conferences around the world and material is presented in a workshop type format featuring real-world scenarios.\n\n## The Perfect Training\n\nSSW invites you to maximise your investment in Microsoft technologies. Led by technical expert Adam Cogan, Database Services Manager for SSW and a Microsoft Regional Director, the seminars will guide you through the latest Microsoft technologies and help you improve your development processes.\n\nGet a head start by attending SSW's series of seminars and conferences led by industry experts.\n\n✅Hours are customizable and flexible\n\n✅Our trainers can come to you\n\n✅Wide range of topics on Microsoft technologies\n\nWhether you want to improve your skills, project or resume, SSW can help you achieve your goals. Our courses cover a broad range of topics in various formats from full-day workshops to evening courses spanning across ten weeks. Small group size guarantees close individual attention given by our knowledgeable and passionate trainers.\n\n> Many thanks to the fine folks at SSW... for coming to our offices and providing the training we needed specifically.\n> — PHILLIP CLARKSON\n\n> \"Eric and SSW have been fantastic. They brought significant experience and pragmatic advice to BuzzNumbers. As a result of their engagement we have implemented a full Project Management process that has dramatically improved team productivity and software quality. SSW had the technical know-how and the direct business implementation experience to deliver on-time results that were above our expectations\"\n> — NICK HOLMES\n\n## Developer Training Courses and Events\n\nMaximise your investment in Microsoft technologies. Led by technical expert Adam Cogan, Database Services Manager for SSW and a Microsoft Regional Director, the seminars will guide you through the latest Microsoft technologies and help you improve your development processes.\n\nView and sort our index of SSW\_[events led by industry experts](https://www.ssw.com.au/ssw/Events/Training/Courses.aspx).\n\nYou can also check our\_[Schedule](https://www.ssw.com.au/ssw/Training/Schedule.aspx)\_to see all upcoming events.\n\n## Power Sessions and Customized Training\n\nPower sessions are developer training presentations focusing on specific subject and are generally 1-2 hours long. They are packed with practical tips on .NET, SQL, Silverlight, Visual Studio and more. Perfect for when you're trying to dig deeper on a particular subject or just want to learn something new. Sessions are rotated on various events and roadshows around the world all year round, including SSW's own\_[Tech Breakfast](https://www.ssw.com.au/ssw/Events/SSWTechBreakfast.aspx)\_and\_[.NET User Group](https://www.ssw.com.au/ssw/NETUG/Sydney.aspx). Meet with fellow developers and discuss pretty much anything.\n\n[Have a look at all Power Sessions](https://www.ssw.com.au/ssw/training/Sessions.aspx)\n"
```

2023-09-07 02:25 UTC, KristenHu commented on public/images/background/SSWTraining.png
**Done**😊

2023-09-07 08:13 UTC, KristenHu commented
As per my conversation with @bradystroud , this PR will be closed since there's too much unknown changes in .tina folder

2023-09-07 08:13 UTC, closed without merging