🐛Update URL of testimonials page
SSWConsulting/SSW.Website pull request #1261
Opened 2023-08-17 10:39 UTC by KristenHu

Fixes #1099 - Update URL of testimonials page

Affected routes:

- `/consulting/video-production/testimonials`

Add done video, screenshots
![image](https://github.com/SSWConsulting/SSW.Website/assets/52522913/944b3ed0-017f-4aac-aafe-763724a450f0)

2023-08-17 22:31 UTC, bradystroud approved these changes
Looks good @KristenHu 

Make sure you add a redirect to Azure Front Door, and fix any links to this page e.g. MegaMenu

2023-08-17 22:33 UTC, bradystroud requested changes
https://app-sswwebsite-9eb3-pr-1261.azurewebsites.net/consulting/video-production

Just realised the link to this page will break once this is merged

<img width="1800" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/38869720/286e7cda-c9f6-4aea-9af6-43beee4fe606">

2023-08-18 09:07 UTC, KristenHu commented
> https://app-sswwebsite-9eb3-pr-1261.azurewebsites.net/consulting/video-production
> 
> Just realised the link to this page will break once this is merged
> 
> <img alt="image" width="1800" src="https://user-images.githubusercontent.com/38869720/261454620-286e7cda-c9f6-4aea-9af6-43beee4fe606.png">

@bradystroud Hey Brady, the showing link has been updated.
![image](https://github.com/SSWConsulting/SSW.Website/assets/52522913/ab6574e8-06e5-4190-a18b-36f3a6740872)

2023-08-19 23:09 UTC, bradystroud approved these changes

2023-08-19 23:09 UTC, merged