💸 Mega Menu - Reduced Bundle Size
SSWConsulting/SSW.Website pull request #1384
Opened 2023-09-11 06:44 UTC by Harry-Ross

- Affected routes: *

- Fixes #1357

2023-09-12 02:40 UTC, bradystroud requested changes
Megamenu images are broken 

<img width="1394" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/38869720/e8538e7a-39cb-4781-8cda-a15ce8fc72ff">

2023-09-12 04:25 UTC, bradystroud commented
Seems to be looking for images using a relative link

<img width="1041" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/38869720/db840e12-7e18-4c98-952c-1a6d21671c0e">

2023-09-12 06:28 UTC, Harry-Ross commented
> Seems to be looking for images using a relative link
> 
> <img alt="image" width="1041" src="https://user-images.githubusercontent.com/38869720/267194886-db840e12-7e18-4c98-952c-1a6d21671c0e.png">

@bradystroud 

Correct, as per https://github.com/SSWConsulting/SSW.Website.Menu.json/pull/99 - this change will fix the images not showing up, but deployments must be coordinated with SSW.People and SSW.Rules to ensure no broken menu across each site.

2023-09-15 06:53 UTC, bradystroud approved these changes

2023-09-15 06:54 UTC, merged