✨ New Page Template - User Group + Sydney Content Migrated
SSWConsulting/SSW.Website pull request #1459
Opened 2023-09-25 02:22 UTC by Harry-Ross

**DRAFT PR**

- Affected routes: `/netug/*`

- Fixed #512

- [x] If adding a new page, I have followed the [SEO checklist](https://www.ssw.com.au/rules/seo-checklist/)

- [ ] Include done video or screenshots

2023-09-29 00:55 UTC, bradystroud approved these changes

2023-10-10 00:27 UTC, bradystroud requested changes
Hey @Harry-Ross 

this is almost perfect, just a few minor things

- [ ] Tylahs image is broken
- [ ] When editing this page, I want it to be super clear what data comes from Tina, and what comes from SharePoint. Not sure how to solve this but would be great if we could have a note in the Tina Editor that says "some fields come from SharePoint, talk to xxx to update them"

![image](https://github.com/SSWConsulting/SSW.Website/assets/38869720/5a003944-a75d-444b-83c1-92950768fa01)
**Figure: Tylahs image broken**

2023-10-11 22:46 UTC, Harry-Ross commented
> Tylahs image is broken

This image is listed in SharePoint as being on ssw.com.au, which means that it will be unbroken upon deployment.

2023-10-11 23:31 UTC, bradystroud approved these changes
LGMT again

2023-10-11 23:31 UTC, merged