✨Add tips to the collection forms
SSWConsulting/SSW.Website pull request #1641
Opened 2023-11-01 09:57 UTC by KristenHu

Add tips to the collection forms to avoid navigation bugs in Tina CMS.

- Affected routes: `/admin/index.html#/collections/new/company/~/`

- Fixed #1404 

![image](https://github.com/SSWConsulting/SSW.Website/assets/52522913/a682b0ce-7c38-4bfc-948a-3da649a98f7c)

2023-11-05 18:56 UTC, bradystroud requested changes

2023-11-05 18:56 UTC, bradystroud commented on .tina/collections/company.tsx
> +              Please fill out all the required labels before navigating to
Make it clear there is a field at the bottom that needs to be filled out before saving.
This is a small PR, you should be able to get this checked by anyone on the team and get it merged asap

2023-11-06 00:46 UTC, Harry-Ross requested changes

2023-11-06 00:46 UTC, Harry-Ross commented on .tina/collections/consulting.tsx
> +    },
Can you move this to `shared-fields.tsx` so we don't violate DRY?

2023-11-09 06:44 UTC, Harry-Ross approved these changes
LGTM 🚢

2023-11-09 06:44 UTC, jeoffreyfischer commented
**Pain**: The tip message was manually added in each page.
**Solution**: I created a single tip message in "shared-fields" and imported it in each page.

- Affected routes: `/admin/`

- Fixed #1404 

![website-PR-004](https://github.com/SSWConsulting/SSW.Website/assets/106663901/f7baabd9-0e8e-4e99-b9fd-85903e707d84)

2023-11-09 22:44 UTC, bradystroud approved these changes

2023-11-09 22:45 UTC, merged