📄Case Study - Template
SSWConsulting/SSW.Website pull request #1766
Opened 2023-11-27 04:04 UTC by amankumarrr

- Affected routes: `/company/clients/shepherd-centre`
- Related #1328 

- [ ] Include done video or screenshots
<img width="947" alt="shepherd-center" src="https://github.com/SSWConsulting/SSW.Website/assets/71385247/c69a9787-056e-4ce5-973b-d0f27c2027c7">

**Figure: Shepherd case study**

2023-11-27 04:07 UTC, bradystroud requested changes

2023-11-27 04:07 UTC, bradystroud commented on .tina/collections/case-study.tsx
> +// };
Do we need this comment?

2023-11-27 04:09 UTC, amankumarrr commented on .tina/collections/case-study.tsx
> +// };
I'm waiting for slot deployment, I'll do some clean up.

2023-11-27 04:14 UTC, amankumarrr commented on .tina/collections/case-study.tsx
> +// };
removed

2023-11-27 11:13 UTC, bradystroud requested changes
One of the breadcrumb links doesn't work

<img width="1510" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/38869720/fec2176f-55fc-4c4f-87c7-60bad2c57359">

**Figure: Broken link**

2023-11-27 11:13 UTC, bradystroud requested changes

2023-11-27 11:13 UTC, bradystroud commented on public/images/POTY-Finalist-inclusion-logo.png
I feel like we would already have this image somewhere.

2023-11-28 01:37 UTC, amankumarrr commented on public/images/POTY-Finalist-inclusion-logo.png
Yes, we are using it on `/company/news`

2023-11-28 01:37 UTC, amankumarrr commented on public/images/POTY-Finalist-inclusion-logo.png
removed the one with this PR

2023-11-28 02:04 UTC, amankumarrr commented
> One of the breadcrumb links doesn't work
> 
> <img alt="image" width="1510" src="https://private-user-images.githubusercontent.com/38869720/285844192-fec2176f-55fc-4c4f-87c7-60bad2c57359.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMzcyMDMsIm5iZiI6MTcwMTEzNjkwMywicGF0aCI6Ii8zODg2OTcyMC8yODU4NDQxOTItZmVjMjE3NmYtNTVmYy00YzRmLTg3YzctNjBiYWQyYzU3MzU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDAyMDE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhYjVjN2UyYTg3NzQ4MWE5MDc1M2I2YmYyZGFjNWRiNWQ3ZDUzYWJkMzE3NTlmY2MxZjBmMmJlYTc0OTQyMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tP-oitWQN8pB-PJp7AV_89RqRd8Xie51BakZvVgTzEU">
> **Figure: Broken link**

As per my conversation with @wicksipedia, we don't need extra path (i.e `case-study`) for this. I've updated PBI and PR accordingly.

2023-11-28 03:50 UTC, bradystroud approved these changes
lgtm

2023-11-28 05:32 UTC, merged