Updating homepage banner
SSWConsulting/SSW.Website pull request #1856
Opened 2023-12-08 04:40 UTC by ae-cher-ssw

Updating banner per Cammy email request RE: Full Stack User Group | update banner for December talk

2023-12-08 04:41 UTC, sethdailyssw approved these changes

2023-12-08 05:28 UTC, bradystroud requested changes
This doesn't look right, the image is a different shape to all the others.

See the white bar thats been introduced under the other images

<img width="1800" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/38869720/9fd05789-5897-484a-a89c-47d984b26e71">


<img width="1800" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/38869720/1d9ba1cf-7ae8-4136-9fd3-4f0ee0a916c2">

2023-12-08 05:50 UTC, sethdaily approved these changes

2023-12-13 22:51 UTC, bradystroud approved these changes
lgtm

2023-12-13 22:51 UTC, merged