Megamenu - Adding it as an npm component
SSWConsulting/SSW.Website pull request #2127
Opened 2024-02-06 04:52 UTC by amankumarrr

Fixed #2115
Affected Route: `/*`

Screenshot: TODO

2024-02-07 00:01 UTC, jeoffreyfischer requested changes

2024-02-07 00:01 UTC, jeoffreyfischer commented on README.md
> +
⚠️ **Warning**: Changes in the mdx files must be done with TinaCMS. This is because TinaCMS maps mdx files with its fields with specific characters for customized UI (e.g., rich-text field). So avoid direct edits as they may result in build failures or go unnoticed during PR reviews.

2024-02-07 01:17 UTC, amankumarrr commented on README.md
> +
done

2024-02-07 04:07 UTC, jeoffreyfischer approved these changes

2024-02-07 04:07 UTC, jeoffreyfischer commented
LGTM

2024-02-08 04:27 UTC, wicksipedia requested changes
As per our conversation - the ux & seo need to be fixed
We will need to switch over to the new app router - I've updated the issue as well

2024-02-15 23:31 UTC, wicksipedia approved these changes
Heaps better ⭐️

2024-02-19 22:37 UTC, merged