Add recuitment console log
SSWConsulting/SSW.Website pull request #2536
Opened 2024-04-22 10:02 UTC by johnxu16

- Affected routes: 
- /employment  

<br/>

- Fixed #770 

![1713780064454](https://github.com/SSWConsulting/SSW.Website/assets/113034339/62fa6254-443d-4f78-aa7e-9d41879e16b1)

- [ ] If adding a new page, I have followed the [📃 New Webpage](https://github.com/SSWConsulting/SSW.Website/issues/new?assignees=&labels=&projects=&template=new_webpage.yml&title=%F0%9F%93%84+%7B%7B+TITLE+%7D%7D+) issue template

- [x] Include done video or screenshots

2024-05-26 23:33 UTC, bradystroud requested changes

2024-05-26 23:33 UTC, bradystroud commented on recruitment.json
This file should not live in the root of the project - move it somewhere more specific

2024-05-30 05:00 UTC, bradystroud requested changes

2024-05-30 05:00 UTC, bradystroud commented on recruitment.json
As per my conversation with @andrewwaltosssw this should be in Tina

2024-08-03 04:57 UTC, Calinator444 commented
Closing this because we have too many PR slots Open.

@bradystroud Please let me know if the referenced issue is still relevant.

2024-08-03 04:59 UTC, closed without merging