Moved newsletters to root of route folder
SSWConsulting/SSW.Website pull request #2560
Opened 2024-04-29 07:55 UTC by Calinator444

- Affected routes: 

- Fixed #{{ ISSUE NUMBER }}

- [ ] If adding a new page, I have followed the [📃 New Webpage](https://github.com/SSWConsulting/SSW.Website/issues/new?assignees=&labels=&projects=&template=new_webpage.yml&title=%F0%9F%93%84+%7B%7B+TITLE+%7D%7D+) issue template

- [ ] Include done video or screenshots

2024-05-02 02:35 UTC, wicksipedia requested changes

2024-05-02 02:35 UTC, wicksipedia commented on components/blocks/customImage.tsx
> +import type { Collection, Template } from "tinacms";
```suggestion
import type { Template } from "tinacms";
```
as per linter

2024-05-02 02:35 UTC, wicksipedia commented on middleware.ts
> +  let path = url.pathname.toString();
```suggestion
  const path = url.pathname.toString();
```
as per linter

2024-05-02 02:36 UTC, wicksipedia commented
looks like your latest code isn't being built/deployed due to linting errors

2024-05-08 00:40 UTC, closed without merging

2024-05-08 00:41 UTC, Calinator444 commented
@wicksipedia closing this because merging would break all of the images on the site"

I'll hang onto the branch because it will be useful when we integrate a media manager for tina later and we can fix all of the file paths