🔎 Added meta descriptions to all pages without them using gpt 4
SSWConsulting/SSW.Website pull request #2746
Opened 2024-06-14 09:17 UTC by Calinator444

CC: @camillars, @adamcogan, @bradystroud 

### Description 
Robots are definitely coming for my job, but that doesn't mean I can't use AI to help us get some of that SEO cheddar for the time being.
![BiggiecheeseRatGIF](https://github.com/SSWConsulting/SSW.Website/assets/65635198/55c42474-42be-42ab-87cd-5c419be95586)

**Tldr**: I've run a Python script to generate meta descriptions for all of the pages on our main website using the content of the page (All of which are under 150 characters).

**Long version**: I've run a Python script that uses the file structure of the repo to determine which pages should exist on the live site, scrapes the content of the page, and sends it to chatGPT using an API so that it could summarize the content into meta descriptions. I couldn't pass the content of each Markdown file directly into ChatGPT because they're broken up into multiple files. Instead I've used a python library called Selenium to load each page into the browser, wait for the client side scripts to finish running, and then create a snapshot of the page. Afterwards I used another Python library to strip all of the HTML tags from the page leaving only the written content. Finally I sent the written content to chat GPT with a system prompt telling it to summarize the content into a meta description under 150 characters. I had to decrease the temperature of the response to get this to work because when chatGPT's responses are too open-ended and creative it surpassed the character limit. Finally I added a check in the script to query the API again if the response was over 150 characters. Meaning all of these descriptions should definitely be under  150 characters.

### List of Pages
I've included the list of page URLs affected along with their corresponding meta tags to make this easier to review. The page list was also generated by the script so there shouldn't be anything missing.
[seo_descriptions.xlsx](https://github.com/user-attachments/files/15835951/seo_descriptions.xlsx)

### Affected routes
https://ssw.com.au/company/clients
https://ssw.com.au/company/resources
https://ssw.com.au/company/clients/auctions-plus
https://ssw.com.au/company/clients/aurecon
https://ssw.com.au/company/clients/ausgrid
https://ssw.com.au/company/clients/bce
https://ssw.com.au/company/clients/bupa
https://ssw.com.au/company/clients/emove
https://ssw.com.au/company/clients/estate-master
https://ssw.com.au/company/clients/event-cinemas
https://ssw.com.au/company/clients/hearing-australia
https://ssw.com.au/company/clients/hutchison-weller
https://ssw.com.au/company/clients/maximus-imprint
https://ssw.com.au/company/clients/medibank
https://ssw.com.au/company/clients/microsoft-sharepoint-office-forum
https://ssw.com.au/company/clients/pwc
https://ssw.com.au/company/clients/shepherd-centre
https://ssw.com.au/company/clients/sydney-uni
https://ssw.com.au/company/clients/tafe
https://ssw.com.au/company/clients/toll
https://ssw.com.au/company/clients/vulcan-steel
https://ssw.com.au/company/clients/worley-parsons
https://ssw.com.au/company/index/
https://ssw.com.au/employment/
https://ssw.com.au/live/
https://ssw.com.au/logo/ai-hackday
https://ssw.com.au/logo/ai-workshop
https://ssw.com.au/logo/angular-hackday
https://ssw.com.au/logo/angular-workshop
https://ssw.com.au/logo/azure-workshop
https://ssw.com.au/logo/ca-workshop
https://ssw.com.au/logo/codeauditor
https://ssw.com.au/logo/dory
https://ssw.com.au/logo/eagleeye
https://ssw.com.au/logo/firebootcamp
https://ssw.com.au/logo/linkauditor
https://ssw.com.au/logo/maui-hackday
https://ssw.com.au/logo/netug
https://ssw.com.au/logo/past
https://ssw.com.au/logo/smashingbarrier
https://ssw.com.au/logo/sophiebot
https://ssw.com.au/logo/sophiehub
https://ssw.com.au/logo/ssw-rewards
https://ssw.com.au/logo/ssw-rules
https://ssw.com.au/logo/ssw-tv
https://ssw.com.au/logo/ssw
https://ssw.com.au/logo/sugarlearning
https://ssw.com.au/logo/timepro
https://ssw.com.au/logo/yakshaver
https://ssw.com.au/netug/
https://ssw.com.au/netug/present
https://ssw.com.au/advertising
https://ssw.com.au/booknow
https://ssw.com.au/domains-for-sale
https://ssw.com.au/hackday
https://ssw.com.au/new-zealand
https://ssw.com.au/products/rewards

2024-06-16 23:55 UTC, bradystroud requested changes
Hey Caleb, the descriptions look good! Only feedback is I think a bit of documentation would be really good here

2024-06-16 23:55 UTC, bradystroud commented on content/seo_description_filler.py
Move this to a scripts folder, also add a README to the folder that explains what this script was used for (for future reference)

e.g. I wrote this for the rules one 
https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/scripts/generateSeoDescriptions/README.md

2024-06-17 02:10 UTC, Calinator444 commented on content/seo_description_filler.py
Done - I added some docs for running the script. If it will need to be routinely run switching away from the ChatGPT implementation should be high priority.

2024-06-18 05:35 UTC, bradystroud approved these changes
LGTM

2024-06-18 07:23 UTC, merged