✨Add T&C page to consulting pages, and create a layout for T&C page.
SSWConsulting/SSW.Website pull request #347
Opened 2023-03-03 07:07 UTC by KristenHu

Still got many work to do:

- [ ] Add agreement form in T&C page
- [ ] Extract the former consulting layout as a component then import it to the consluting page
- [ ] Allow the consulting page choose different layout according to the page settings
- [ ] Add CODEOWNER to T&C content

2023-03-20 01:33 UTC, wicksipedia commented
Are you able to make it a little more like the current implementation:
- add zebra striping to the table
- t&c clauses in 2 columns

2023-03-24 04:13 UTC, bradystroud requested changes
Breadcrumb is missing

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/38869720/227422623-817189d5-947a-4369-a272-82acfbacaea5.png">

2023-03-24 06:08 UTC, bradystroud requested changes
<img width="960" alt="image" src="https://user-images.githubusercontent.com/38869720/227438425-8ccbe5cd-1795-408f-8517-a8543235e341.png">

this should be seperate like the v1 
![image](https://user-images.githubusercontent.com/38869720/227438606-eaf0b4b9-8bef-41f5-b75f-7877ba01fbb0.png)

2023-03-24 06:09 UTC, bradystroud requested changes
Make address box big
<img width="960" alt="image" src="https://user-images.githubusercontent.com/38869720/227438756-e05d5fc8-bc63-4136-8720-ce1363315244.png">
**Figure: Too small for address**

See v1 page
https://www.ssw.com.au/ssw/Consulting/Terms-and-Conditions/
![image](https://user-images.githubusercontent.com/38869720/227438879-7e4fc55e-063d-44f3-8596-3cdf0a7c92e2.png)

2023-03-24 06:11 UTC, bradystroud requested changes
Add a placeholder to this field like the v1

![image](https://user-images.githubusercontent.com/38869720/227439280-faac8137-6556-4078-ba4c-b1cd09a04d8c.png)

2023-03-27 03:26 UTC, wicksipedia requested changes

2023-03-27 03:26 UTC, wicksipedia commented on content/pages/terms-and-conditions.mdx
> +    Note: The Sydney Metropolitan area is defined by the council areas in the Sydney Inner (SI) and Sydney Outer (SO) regions listed by the [Department of Local Government](http://www.cityofsydney.ns
This link results in a 404 - @UlyssesMaclaren do you have a better link?

2023-03-28 23:53 UTC, UlyssesMaclaren commented on content/pages/terms-and-conditions.mdx
> +    Note: The Sydney Metropolitan area is defined by the council areas in the Sydney Inner (SI) and Sydney Outer (SO) regions listed by the [Department of Local Government](http://www.cityofsydney.ns
someone called me the other day with an alternative that worked. I think it was Harry

2023-03-29 23:17 UTC, wicksipedia approved these changes

2023-03-30 00:00 UTC, merged