Collection - adding opportunities
SSWConsulting/SSW.Website pull request #451
Opened 2023-03-24 05:43 UTC by amankumarrr

closes #445

2023-03-27 04:12 UTC, Harry-Ross requested changes

2023-03-27 04:12 UTC, Harry-Ross commented on .tina/collections/opportunities.tsx
> +			},
You could also write it this way - better to have `const` in the code instead of `var`.
```suggestion
				validate: (value) => {
					const locations = value?.map((x) => x.location);
	                const locArray: string[] = [];
                
	                locations?.forEach((loc) => {
		                if (!locArray.includes(loc)) {
			                locArray.push(loc);
		                } else {
			                return "You cannot have same location multiple times!";
		                }
	                });
				},
			},
```

2023-03-27 04:12 UTC, Harry-Ross commented on components/util/constants.tsx
> +];
- Move to separate file in `/components/util/constants`
- Consider changing to array of strings

2023-03-31 02:15 UTC, bradystroud approved these changes
LGTM💰

2023-03-31 02:15 UTC, Harry-Ross approved these changes
lgtm

2023-03-31 02:20 UTC, merged