34 internship page
SSWConsulting/SSW.Website pull request #477
Opened 2023-04-03 00:05 UTC by BrookJeynes

2023-04-24 01:22 UTC, bradystroud requested changes

2023-04-24 01:22 UTC, bradystroud commented on components/blocks/clientLogos.tsx
> +};
Should these be hardcoded?
Can we move them to tina?

2023-04-24 01:22 UTC, bradystroud commented on components/blocks/clientLogos.tsx
> +    // Todo: Find a way to have no fields - the one below is to satisfy compiler
Investigate this

2023-04-24 01:22 UTC, bradystroud commented on components/training/training.module.css
> +/* } */
Remove if not used
```suggestion
```

2023-04-24 01:22 UTC, bradystroud commented on content/internship/fullstack.mdx
Whats this for?

2023-04-24 01:22 UTC, bradystroud commented on content/training/fullstack.mdx
> +
🤔

2023-04-24 04:47 UTC, Harry-Ross commented on components/blocks/recurringEvent.tsx
> +};
Maybe change this function name to something clearer - call it some form of countdown component

2023-04-24 04:53 UTC, Harry-Ross commented on components/training/trainingHeader.tsx
> +            // autoPlay
remove

2023-04-24 05:04 UTC, Harry-Ross commented on components/blocks/mdxComponentRenderer.tsx
> +    };
Should this also take in a day?

2023-04-24 05:06 UTC, Harry-Ross commented on components/blocks/verticalListItem.tsx
> +    const iconScale = data?.iconScale ? data?.iconScale : 1;
Can be `const iconScale = data?.iconScale | 1`

2023-04-24 05:08 UTC, Harry-Ross commented on components/blocks/verticalListItem.tsx
> +                    height={65}
Does it matter if height is multiplied by iconScale

2023-04-24 05:10 UTC, Harry-Ross commented on components/training/trainingHeader.tsx
> +            style={{ backgroundImage: `url(${data?.heroBackground})` }}
what happens if its undefined

2023-04-24 05:23 UTC, Harry-Ross commented on components/training/training.module.css
> +}
Add comment to justify CSS module

2023-04-24 05:54 UTC, Harry-Ross commented on styles.css
> +        font-family: --var(open-sans-font), Helvetica Neue, Helvetica, Arial, sans-serif;
@wicksipedia is this fine with the next/font additions you made? same with the changes in tailwind.config.js

2023-04-24 05:55 UTC, Harry-Ross commented
Approved once my comments are fixed

2023-04-24 06:40 UTC, wicksipedia commented on components/blocks/clientLogos.tsx
> +    // Todo: Find a way to have no fields - the one below is to satisfy compiler
the schema could be the list of client images

2023-04-24 06:41 UTC, wicksipedia commented on tailwind.config.js
> +            maxWidth: 0,
can we kill this line?

2023-05-08 00:54 UTC, bradystroud commented on components/blocks/clientLogos.tsx
> +};
As per our conversation, create a tech debt PBI to deal with this later

2023-05-08 01:09 UTC, BrookJeynes commented on components/blocks/clientLogos.tsx
> +};
https://github.com/SSWConsulting/SSW.Website-v3/issues/583

2023-05-08 01:10 UTC, BrookJeynes commented on components/blocks/clientLogos.tsx
> +    // Todo: Find a way to have no fields - the one below is to satisfy compiler
As per my conversation this will be resolved in https://github.com/SSWConsulting/SSW.Website-v3/issues/583

2023-05-08 01:11 UTC, bradystroud approved these changes

2023-05-08 01:30 UTC, wicksipedia approved these changes

2023-05-08 01:30 UTC, wicksipedia approved these changes

2023-05-08 04:07 UTC, merged