Page - Educational
SSWConsulting/SSW.Website pull request #550
Opened 2023-04-27 02:45 UTC by jimmidier

Closes #299 

![image](https://user-images.githubusercontent.com/16027480/234746685-b8ebf0d5-00ee-4cc4-a4a1-e9e7ac85285a.png)

2023-05-09 23:03 UTC, bradystroud requested changes
Not a fan of how this button has the icons.
Only links should have those icons

![image](https://github.com/SSWConsulting/SSW.Website-v3/assets/38869720/274eb363-3a15-4e44-b0bc-41eb8b1f9542)
**Figure: Icons look out of place**

2023-05-10 02:37 UTC, jimmidier commented
> Not a fan of how this button has the icons. Only links should have those icons
> 
> ![image](https://user-images.githubusercontent.com/38869720/237238626-274eb363-3a15-4e44-b0bc-41eb8b1f9542.png) **Figure: Icons look out of place**
> 
> I understand these icons are on the old website, but it looks like a bug.

Done - Removed the icons. Please re-review

2023-05-10 05:49 UTC, bradystroud requested changes
As per our conversation, there are a few changes 🙂

2023-05-10 05:49 UTC, bradystroud commented on public/images/icons/IconPdf.png
Remove if not used

2023-05-10 05:49 UTC, bradystroud commented on public/images/icons/arrow-right.png
Remove if not used

2023-05-10 05:49 UTC, bradystroud commented on pages/educational/index.tsx
> +        />
These hardcoded strings are not ideal.

Copy the approach used by the consulting page template

https://github.com/SSWConsulting/SSW.Website-v3/blob/0cc5673ad1ca0ac88daba4ce2bea45b882184082/pages/consulting/[filename].tsx#L62

2023-05-10 05:49 UTC, bradystroud commented on pages/educational/index.tsx
> +      <SEO seo={{ ...node.seo, canonical: "/educational" }} />
Check out
https://github.com/SSWConsulting/SSW.Website-v3/blob/main/pages/consulting/[filename].tsx#L202

2023-05-10 05:49 UTC, bradystroud commented on .tina/collections/educational.tsx
> +        ),
![image](https://github.com/SSWConsulting/SSW.Website-v3/assets/38869720/bed2c4c5-b8e3-4b6c-aa33-855aedbcaf90)

2023-05-15 02:42 UTC, jimmidier commented on public/images/icons/arrow-right.png
This icon is being used thus not removed

2023-05-15 03:20 UTC, bradystroud approved these changes

2023-05-15 03:20 UTC, merged