#484 DevEx - Create a Dev Container
SSWConsulting/SSW.Website pull request #571
Opened 2023-05-04 05:53 UTC by johnxu77

Add devcontainer support based on https://ssw.com.au/rules/dev-containers

2023-05-16 07:14 UTC, bradystroud requested changes
As per our conversation, please add the new steps to the readme.

2023-05-16 07:14 UTC, bradystroud commented on .devcontainer/Dockerfile
> +# && apt-get -y install --no-install-recommends git
Remove these

2023-05-16 07:36 UTC, johnxu77 commented on .devcontainer/Dockerfile
> +# && apt-get -y install --no-install-recommends git
Done - Removed 🙂

2023-05-16 07:57 UTC, johnxu16 commented
> ## Try 2 (init devcontainer on windows 11)
> * [x]  image build
> * [x]  yarn install
> * [x]  extensions
> * [x]  port forwarding
> 
> ![MicrosoftTeams-image](https://user-images.githubusercontent.com/113034339/236376513-25bf20a0-3aea-44ef-871d-d946d0170800.png) **Figure: Yarn failed to install**
> 
> ![image](https://user-images.githubusercontent.com/113034339/236382113-e4278479-8513-4d25-911c-d6424bee9c2a.png) **Figure: EIO: i/o error**

After freeing up some space in c drive, problems solved

2023-05-18 07:51 UTC, bradystroud approved these changes

2023-05-18 07:51 UTC, merged