💄Update success UX
SSWConsulting/SSW.Website pull request #762
Opened 2023-06-06 09:15 UTC by KristenHu

closed #733 

Affected routes:

- `/consulting/remote-work` etc.

![image](https://github.com/SSWConsulting/SSW.Website/assets/52522913/1bf16b32-b8f9-43ad-9a45-aaff82c33072)

2023-06-07 02:12 UTC, jaydenalchin commented
Hi @KristenHu thanks for getting onto this so quickly! Here's my feedback: 

- [ ] Modals - Instead of opening a new modal on top of the existing one, the existing window should stay open, and the content should change to display this confirmation after user clicks Submit. 
- [ ] Modals - Use the same styling as the existing modal for this confirmation modal. 
- [ ] Content - Add a line break after the first sentence of the description text (after "submitted successfully").

2023-06-11 23:52 UTC, jaydenalchin commented
Hi @KristenHu this is looking very nice! 
CC @bradystroud 

1. Please use the dark theme success toast as per https://fkhadra.github.io/react-toastify/introduction/
2. Move the toast notification top-right instead of top-center
3. Simplify the confirmation message a bit more e.g. "Form submitted. We'll be in contact as soon as possible"
4. If possible, left-justify the text inside the toast.

2023-06-12 08:54 UTC, KristenHu commented
> Hi @KristenHu this is looking very nice! CC @bradystroud
> 
> 1. Please use the dark theme success toast as per https://fkhadra.github.io/react-toastify/introduction/
> 2. Move the toast notification top-right instead of top-center
> 3. Simplify the confirmation message a bit more e.g. "Form submitted. We'll be in contact as soon as possible"
> 4. If possible, left-justify the text inside the toast.

Hey @jaydenalchin (CC @bradystroud ),

All done, check please😊

FYI: I just adjust the style of the booking form on consulting page, I'll update the toast on the educational page after this version's toast gets passed.

2023-06-12 22:07 UTC, jaydenalchin commented
> Hey @jaydenalchin (CC @bradystroud ),
> 
> All done, check please😊


@KristenHu Test passed!  🎉

2023-06-12 23:44 UTC, bradystroud requested changes

2023-06-12 23:44 UTC, bradystroud commented on components/bookingButton/bookingButton.tsx
> +
Looks like this code is duplicated. Can we reuse it?

2023-06-12 23:54 UTC, jaydenalchin approved these changes

2023-06-13 22:29 UTC, bradystroud approved these changes
LGTM 🏄‍♂️

2023-06-13 23:11 UTC, merged