Disable Button - Consulting enquiry and spinner on loading
SSWConsulting/SSW.Website pull request #799
Opened 2023-06-13 04:23 UTC by amankumarrr

fixes #728

2023-06-13 06:13 UTC, bradystroud requested changes

2023-06-13 06:13 UTC, bradystroud commented on components/spinner/spinner.tsx
This is not how we do icons. Please use FontAwesome.

2023-06-13 07:05 UTC, jaydenalchin approved these changes

2023-06-13 07:05 UTC, jaydenalchin commented on components/spinner/spinner.tsx
> +  <svg
From a UX perspective this is looking great! But we should use fontawesome icons instead of svgs 

e.g. class="fa-solid fa-spinner"

2023-06-13 07:09 UTC, amankumarrr commented on components/spinner/spinner.tsx
> +  <svg
done - I'm using Font Awesome Icon now, GIF is updated in the description above.

2023-06-13 23:55 UTC, bradystroud commented on styles.css
> +  }
💣

```suggestion
```

2023-06-14 00:00 UTC, bradystroud approved these changes
LGTM 🛫

2023-06-14 00:46 UTC, merged