💄 Newsletter Signup - implement redesign
SSWConsulting/SSW.Website pull request #802
Opened 2023-06-13 07:07 UTC by KristenHu

Closed #755 - Reskin the signup component

Affected routes:

-`/newsletters`
![image](https://github.com/SSWConsulting/SSW.Website/assets/52522913/7372d431-250f-463c-9621-7ca259cadd65)

2023-06-14 03:06 UTC, bradystroud requested changes

2023-06-14 03:06 UTC, bradystroud commented on components/blocks/subNewsLetters.tsx
> +        {/* <div className=""> */}
Can we remove this?

2023-06-14 03:06 UTC, bradystroud commented on components/blocks/subNewsLetters.tsx
> +        {/* </div> */}
And this :)

2023-06-14 04:04 UTC, bradystroud requested changes
<img width="460" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/38869720/15580b84-dfbf-4dbd-80c9-3714316f40ea">

Make this icon look like the Submit button on the booking form

<img width="440" alt="image" src="https://github.com/SSWConsulting/SSW.Website/assets/38869720/3a781049-6221-48a1-a82c-80cf967440d3">

**Figure: ✅ New icon looks much nicer**

2023-06-16 00:21 UTC, bradystroud requested changes
Hey @KristenHu 

Love the new design 🙂

1. The signup button should be disabled while the signup is in progress (like the submit button on the booking form)
2. Getting an error when signing up 😕

![](https://github.com/SSWConsulting/SSW.Website/assets/38869720/473d5c6d-0b30-43a9-aa25-fcee9e5a36dc)
**Figure: signup not working**

2023-06-19 02:04 UTC, KristenHu commented on components/blocks/subNewsLetters.tsx
> +        {/* <div className=""> */}
Done, sorry about that😊

2023-06-19 02:04 UTC, KristenHu commented on components/blocks/subNewsLetters.tsx
> +        {/* </div> */}
Done

2023-06-19 02:50 UTC, KristenHu commented
> Hey @KristenHu
> 
> Love the new design 🙂
> 
> 1. The signup button should be disabled while the signup is in progress (like the submit button on the booking form)
> 2. Getting an error when signing up 😕
> 
> ![](https://user-images.githubusercontent.com/38869720/246280378-473d5c6d-0b30-43a9-aa25-fcee9e5a36dc.png) **Figure: signup not working**


1. The signup button should be disabled while the signup is in progress (like the submit button on the booking form)
**Done.**
2. Getting an error when signing up 😕
That's an error related to the backend API, I think it's better to create a new issue to fix it😃

2023-06-19 07:11 UTC, bradystroud approved these changes
LGTM 🥳

2023-06-19 07:11 UTC, merged